apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.254.201-10.0.254.209

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool 
  namespace: metallb-system
 
